//go:build ignore

package main

import (
	"os"
	"strings"
	"text/template"
)

const tmpl = `// Code generated by go generate; DO NOT EDIT.
// To regenerate, run: go generate

package main

var emojis = []string{
{{- range .}}
	{{printf "%q" .}},
{{- end}}
}
`

func main() {
	data, _ := os.ReadFile("all_emojis.txt")

	var emojis []string
	for _, emoji := range strings.Split(string(data), ",") {
		if trimmed := strings.TrimSpace(emoji); trimmed != "" {
			emojis = append(emojis, trimmed)
		}
	}

	f, _ := os.Create("emojis_generated.go")
	defer f.Close()

	t := template.Must(template.New("emojis").Parse(tmpl))
	t.Execute(f, emojis)
}
